language: go
go:
  - 1.12

env:
  - GO111MODULE=on

install: true

script:
  - "go vet -mod=vendor $(go list ./... | grep -v vendor)"
  - "go test -mod=vendor $(go list ./... | grep -v vendor)"
  - "make"
